apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-minio
  namespace: rawdrive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus-minio
  template:
    metadata:
      labels:
        app: milvus-minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2023-03-20T20-16-18Z
        command:
        - minio
        - server
        - /minio_data
        - --console-address
        - :9001
        env:
        - name: MINIO_ACCESS_KEY
          value: minioadmin
        - name: MINIO_SECRET_KEY
          value: minioadmin
        ports:
        - containerPort: 9000
        - containerPort: 9001
        volumeMounts:
        - name: minio-data
          mountPath: /minio_data
      volumes:
      - name: minio-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: rawdrive
spec:
  ports:
  - name: api
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
  selector:
    app: milvus-minio
