"""Pydantic schemas for request/response validation."""

from src.schemas.common import PaginationMeta, ErrorResponse, ErrorDetail
from src.schemas.client import (
    ClientCreate,
    ClientUpdate,
    ClientResponse,
    ClientListItem,
    ClientListResponse,
    ClientSearchParams,
)
from src.schemas.contact import (
    ContactCreate,
    ContactUpdate,
    ContactResponse,
)
from src.schemas.address import (
    AddressCreate,
    AddressUpdate,
    AddressResponse,
)
from src.schemas.tag import (
    TagCreate,
    TagUpdate,
    TagResponse,
    TagListResponse,
    TagAssignRequest,
    TagUnassignRequest,
)
from src.schemas.gallery_link import (
    GalleryLinkCreate,
    GalleryLinkUpdate,
    GalleryLinkResponse,
    GalleryLinkListResponse,
    ProofingSummaryResponse,
)
from src.schemas.activity import (
    ActivityCreate,
    ActivityUpdate,
    ActivityResponse,
    ActivityListResponse,
    NoteCreate,
    ActivitySearchParams,
)
from src.schemas.communication import (
    CommunicationCreate,
    CommunicationUpdate,
    CommunicationResponse,
    CommunicationListResponse,
    CompleteFollowUpRequest,
)
from src.schemas.smart_list import (
    SmartListCreate,
    SmartListUpdate,
    SmartListResponse,
    SmartListListResponse,
    SmartListEvaluationResponse,
)
from src.schemas.import_export import ImportResult, ExportFormat, ClientImportRow
from src.schemas.bulk_ops import (
    BulkTagRequest,
    BulkStatusChangeRequest,
    BulkDeleteRequest,
    BulkOperationResult,
)
from src.schemas.duplicate import (
    DuplicateCandidate,
    DuplicateGroup,
    DuplicateDetectionRequest,
    DuplicateDetectionResponse,
    MergeStrategy,
    MergeResult,
    MergeAuditTrail,
    SimilarityMatch,
)
from src.schemas.visitor import (
    VisitorConversionRequest,
    VisitorConversionResult,
    AutoMatchRequest,
    AutoMatchResult,
    VisitorInfo,
    BulkConversionRequest,
    BulkConversionResult,
)
from src.schemas.analytics import (
    AnalyticsTimeRange,
    ClientEngagementMetrics,
    WorkspaceAnalyticsSummary,
    TimeSeriesDataPoint,
    TimeSeriesMetric,
    ClientActivityTrend,
    TagAnalytics,
    CommunicationAnalytics,
    GalleryEngagementAnalytics,
    AnalyticsRequest,
)

__all__ = [
    "PaginationMeta",
    "ErrorResponse",
    "ErrorDetail",
    "ClientCreate",
    "ClientUpdate",
    "ClientResponse",
    "ClientListItem",
    "ClientListResponse",
    "ClientSearchParams",
    "ContactCreate",
    "ContactUpdate",
    "ContactResponse",
    "AddressCreate",
    "AddressUpdate",
    "AddressResponse",
    "TagCreate",
    "TagUpdate",
    "TagResponse",
    "TagListResponse",
    "TagAssignRequest",
    "TagUnassignRequest",
    "GalleryLinkCreate",
    "GalleryLinkUpdate",
    "GalleryLinkResponse",
    "GalleryLinkListResponse",
    "ProofingSummaryResponse",
    "ActivityCreate",
    "ActivityUpdate",
    "ActivityResponse",
    "ActivityListResponse",
    "NoteCreate",
    "ActivitySearchParams",
    "CommunicationCreate",
    "CommunicationUpdate",
    "CommunicationResponse",
    "CommunicationListResponse",
    "CompleteFollowUpRequest",
    "SmartListCreate",
    "SmartListUpdate",
    "SmartListResponse",
    "SmartListListResponse",
    "SmartListEvaluationResponse",
    "ImportResult",
    "ExportFormat",
    "ClientImportRow",
    "BulkTagRequest",
    "BulkStatusChangeRequest",
    "BulkDeleteRequest",
    "BulkOperationResult",
    "DuplicateCandidate",
    "DuplicateGroup",
    "DuplicateDetectionRequest",
    "DuplicateDetectionResponse",
    "MergeStrategy",
    "MergeResult",
    "MergeAuditTrail",
    "SimilarityMatch",
    "VisitorConversionRequest",
    "VisitorConversionResult",
    "AutoMatchRequest",
    "AutoMatchResult",
    "VisitorInfo",
    "BulkConversionRequest",
    "BulkConversionResult",
    "AnalyticsTimeRange",
    "ClientEngagementMetrics",
    "WorkspaceAnalyticsSummary",
    "TimeSeriesDataPoint",
    "TimeSeriesMetric",
    "ClientActivityTrend",
    "TagAnalytics",
    "CommunicationAnalytics",
    "GalleryEngagementAnalytics",
    "AnalyticsRequest",
]
