DROP TABLE IF EXISTS follow_ups CASCADE;
DROP TABLE IF EXISTS deals CASCADE;
ALTER TABLE leads DROP CONSTRAINT IF EXISTS leads_converted_contact_fk;
DROP TABLE IF EXISTS contacts CASCADE;
DROP TABLE IF EXISTS leads CASCADE;
