package auth

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"math/big"
	"net/url"
	"strings"
	"sync"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"github.com/rawdrive/backend/internal/passwordpolicy"
	"golang.org/x/crypto/bcrypt"
)

// F-103 (audit 2026-05-30): jwtIssuer / jwtAudience bind every access token this
// service mints to a single logical service identity. Without them a token
// signed by this key would be accepted by any peer that merely trusts the same
// RS256 public key (token-confusion / cross-service replay). These are public
// identifiers, not secrets, so they are a compile-time constant rather than a
// platform_settings/env value. ParseAccessToken now enforces both via
// jwt.WithIssuer / jwt.WithAudience.
const (
	jwtIssuer   = "rawdrive-api"
	jwtAudience = "rawdrive-api"
)

// ──────────────────────────── Types ────────────────────────────

type User struct {
	ID          string
	Email       string
	DisplayName string
	AvatarURL   string
	// EmailVerified reports whether the local account has completed email
	// activation. The Google callback uses this to decide whether it is safe
	// to auto-link an existing local account: linking to an *unverified*
	// local account would let an attacker who pre-registered the victim's
	// email (without ever verifying it) take it over via Google (S1-G1).
	EmailVerified bool
}

type OAuthToken struct {
	AccessToken string
}

type OAuthProfile struct {
	Email       string
	DisplayName string
	AvatarURL   string
	ProviderID  string
	// EmailVerified mirrors Google's userinfo "email_verified" claim. The
	// callback REJECTS the sign-in when this is false: an unverified Google
	// email proves nothing about ownership and must never be allowed to
	// auto-link to (or create) a local account (S1-G1 / AREA-AUTH-4).
	EmailVerified bool
}

// ──────────────────────────── Interfaces ────────────────────────────

type EmailDelivery interface {
	SendOTP(ctx context.Context, email, code string) error
}

type OAuthProvider interface {
	ExchangeCode(ctx context.Context, code string) (*OAuthToken, error)
	GetProfile(ctx context.Context, token *OAuthToken) (*OAuthProfile, error)
}

type UserStore interface {
	FindByEmail(ctx context.Context, email string) (*User, error)
	// FindByProviderSubject resolves the local account already linked to a
	// given (provider, provider_subject) pair. Returns (nil, nil) when no
	// link exists. This is the PRIMARY identity resolution for repeat OAuth
	// logins (S1-G2 / AREA-AUTH-3): once a Google identity has been linked,
	// the stable Google "sub" — not the mutable email — decides who logs in.
	FindByProviderSubject(ctx context.Context, provider, providerSubject string) (*User, error)
	Create(ctx context.Context, u *User) (*User, error)
	LinkOAuth(ctx context.Context, userID, provider, providerID string) error
	// BackfillProfile updates empty display name and/or avatar URL, e.g.
	// when an email-registered user later signs in via Google and the
	// profile provides data they did not enter during registration.
	// Either field may be empty to skip that update.
	BackfillProfile(ctx context.Context, userID, displayName, avatarURL string) error
	// MarkEmailVerified flips users.email_verified to TRUE. The Google
	// callback calls this when it creates a new account from a Google-verified
	// identity so the resulting local account is born already activated
	// (it has proven email ownership via Google, so the email-OTP step is
	// not required for the OAuth-created account).
	MarkEmailVerified(ctx context.Context, userID string) error
}

type SecurityNotifier interface {
	SendSecurityNotification(ctx context.Context, email, message string) error
	// 2026-05-19: SendPasswordResetOTP delivers the 6-digit one-time
	// code generated by RequestReset. Previously RequestReset only
	// stashed the OTP in memory and never emailed it — the user saw
	// the "redirecting to reset page" message and then sat on
	// /reset-password with no code to enter. Implementations should
	// log + suppress send failures rather than propagate (the
	// enumeration-defense contract requires RequestReset to look
	// identical for registered and unregistered emails regardless
	// of email-transport state).
	SendPasswordResetOTP(ctx context.Context, email, code string, expirySeconds int) error
}

type PasswordStore interface {
	FindByEmail(ctx context.Context, email string) (*User, error)
	UpdatePassword(ctx context.Context, email, hashedPassword string) error
	RecordFailedAttempt(ctx context.Context, email string) (int, error)
	IsLocked(ctx context.Context, email string) (bool, error)
}

// ──────────────────────────── OTP Service ────────────────────────────

type OTPConfig struct {
	CodeLength      int
	Expiry          time.Duration
	MaxAttempts     int
	RateLimitMax    int
	RateLimitWindow time.Duration
}

type otpEntry struct {
	code      string
	expiresAt time.Time
	attempts  int
	used      bool
}

type OTPService interface {
	Generate(ctx context.Context, identifier string) (string, error)
	Validate(ctx context.Context, identifier, code string) (bool, error)
}

type otpService struct {
	config   OTPConfig
	delivery EmailDelivery
	mu       sync.Mutex
	entries  map[string]*otpEntry
	// rate limiting: identifier -> list of generation timestamps
	rateLog map[string][]time.Time
}

func NewOTPService(config OTPConfig) OTPService {
	return &otpService{
		config:  config,
		entries: make(map[string]*otpEntry),
		rateLog: make(map[string][]time.Time),
	}
}

func NewOTPServiceWithDelivery(config OTPConfig, delivery EmailDelivery) OTPService {
	return &otpService{
		config:   config,
		delivery: delivery,
		entries:  make(map[string]*otpEntry),
		rateLog:  make(map[string][]time.Time),
	}
}

func generateCode(length int) (string, error) {
	code := ""
	for i := 0; i < length; i++ {
		n, err := rand.Int(rand.Reader, big.NewInt(10))
		if err != nil {
			return "", err
		}
		code += fmt.Sprintf("%d", n.Int64())
	}
	return code, nil
}

func (s *otpService) Generate(ctx context.Context, identifier string) (string, error) {
	// F-032 (audit 2026-05-30): only the in-memory entries/rateLog maps are
	// shared mutable state, so the mutex is held for that read/write window
	// alone. SendOTP is an SMTP round-trip and must run lock-free, otherwise a
	// single slow/timing-out send serializes every concurrent registration OTP
	// behind one global lock (effective DoS on sign-up). On send failure we
	// re-acquire and roll back both the stored entry and the rate-log slot so a
	// failed send leaves no usable code and does not consume the caller's quota.
	s.mu.Lock()

	// Rate limiting
	now := time.Now()
	windowStart := now.Add(-s.config.RateLimitWindow)
	var recent []time.Time
	for _, t := range s.rateLog[identifier] {
		if t.After(windowStart) {
			recent = append(recent, t)
		}
	}
	if len(recent) >= s.config.RateLimitMax {
		s.mu.Unlock()
		return "", errors.New("rate limit exceeded")
	}

	code, err := generateCode(s.config.CodeLength)
	if err != nil {
		s.mu.Unlock()
		return "", err
	}

	s.entries[identifier] = &otpEntry{
		code:      code,
		expiresAt: now.Add(s.config.Expiry),
		attempts:  0,
		used:      false,
	}
	s.rateLog[identifier] = append(recent, now)
	s.mu.Unlock()

	if s.delivery != nil {
		if err := s.delivery.SendOTP(ctx, identifier, code); err != nil {
			// Roll back the entry and the rate-log slot we just recorded so the
			// failed send is not chargeable and the unsent code is unusable.
			s.mu.Lock()
			delete(s.entries, identifier)
			s.rateLog[identifier] = recent
			s.mu.Unlock()
			return "", err
		}
	}

	return code, nil
}

func (s *otpService) Validate(ctx context.Context, identifier, code string) (bool, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	entry, ok := s.entries[identifier]
	if !ok {
		return false, nil
	}

	if entry.attempts >= s.config.MaxAttempts {
		return false, errors.New("max attempts exceeded")
	}

	if entry.used {
		return false, nil
	}

	if time.Now().After(entry.expiresAt) {
		return false, nil
	}

	entry.attempts++

	if subtle.ConstantTimeCompare([]byte(entry.code), []byte(code)) != 1 {
		if entry.attempts >= s.config.MaxAttempts {
			// Already counted, next call will error
		}
		return false, nil
	}

	entry.used = true
	return true, nil
}

// ──────────────────────────── JWT Service ────────────────────────────

type JWTConfig struct {
	AccessTokenExpiry  time.Duration
	RefreshTokenExpiry time.Duration
	MaxSessions        int
}

type TokenClaims struct {
	Sub          string
	WorkspaceID  string
	Role         string // Workspace role: Owner/Admin/Editor/Viewer
	PlatformRole string // Platform role: super_admin/admin/dealer/photographer/team_member/client
	StateID      string
	// F-007 (M17 hardening wave 1): MFAVerified is true iff this access token
	// was issued after a successful TOTP verification in the login flow.
	// Middleware gates TOTP-mandatory roles (platform_admin, platform_staff,
	// workspace_owner, workspace_admin, workspace_member) on MFAVerified==true
	// OR an active grace window (users.mfa_grace_until).
	// Zero value (false) is the safe default for legacy tokens without the claim.
	MFAVerified bool
	// S5-G1 (audit HIGH): Impersonation is true iff this access token was minted
	// by an admin impersonating a tenant (AdminUserService.ImpersonateUser).
	// Middleware (RejectImpersonationWrites) gates mutating HTTP methods on this
	// flag so impersonated sessions are truly read-only. Zero value (false) is the
	// safe default for every normal login/refresh token — it is set in exactly one
	// place (ImpersonateUser) and omitted/false everywhere else.
	Impersonation bool
	ExpiresAt     time.Time
}

type RefreshTokenInfo struct {
	Sub       string
	FamilyID  string
	ExpiresAt time.Time
}

type JWTService interface {
	GenerateAccessToken(ctx context.Context, claims TokenClaims) (string, error)
	ParseAccessToken(ctx context.Context, tokenStr string) (*TokenClaims, error)
	GenerateRefreshToken(ctx context.Context, userID, familyID string) (string, error)
	GenerateRefreshTokenWithClaims(ctx context.Context, userID, familyID, workspaceID, role, platformRole, stateID string) (string, error)
	// F-007 (M17 wave 2): variant that persists the mfa_verified state
	// of the minting login. RotateRefreshToken carries this forward so
	// refreshed access tokens keep their MFA state.
	GenerateRefreshTokenWithMFA(ctx context.Context, userID, familyID, workspaceID, role, platformRole, stateID string, mfaVerified bool) (string, error)
	RotateRefreshToken(ctx context.Context, oldToken string) (newAccess string, newRefresh string, err error)
	InspectRefreshToken(ctx context.Context, tokenStr string) (*RefreshTokenInfo, error)
	RevokeSession(ctx context.Context, familyID string) error
}

// refreshEntry is removed in F-006 Part B — state lives in
// RefreshSessionStore / RefreshSessionEntry now (see refresh_session_store.go).

type jwtService struct {
	config     JWTConfig
	privateKey *rsa.PrivateKey
	publicKey  *rsa.PublicKey
	mu         sync.Mutex
	// F-006 Part B (audit 2026-04-10): refresh session state lives
	// behind the RefreshSessionStore interface so production can wire a
	// DB-backed implementation (survives restarts, multi-instance safe)
	// while tests continue to use the default in-memory store.
	refreshStore RefreshSessionStore
}

func NewJWTService(config JWTConfig) JWTService {
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		log.Fatalf("auth: failed to generate RSA key for JWT service: %v", err)
	}
	return &jwtService{
		config:       config,
		privateKey:   key,
		publicKey:    &key.PublicKey,
		refreshStore: NewInMemoryRefreshStore(),
	}
}

// WithRefreshStore replaces the default in-memory refresh session store
// with a caller-provided implementation. main.go uses this during
// bootstrap to wire the DB-backed RefreshSessionRepo so refresh sessions
// survive service restarts (F-006 Part B). Returns the same service
// pointer for call chaining. Passing nil is a no-op — the existing
// in-memory store is retained.
func (s *jwtService) WithRefreshStore(store RefreshSessionStore) JWTService {
	if store == nil {
		return s
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.refreshStore = store
	return s
}

func (s *jwtService) GenerateAccessToken(ctx context.Context, claims TokenClaims) (string, error) {
	if claims.Sub == "" || claims.WorkspaceID == "" || claims.Role == "" || claims.StateID == "" {
		return "", errors.New("missing required claims")
	}
	if claims.PlatformRole == "" {
		claims.PlatformRole = "photographer"
	}

	now := time.Now()
	token := jwt.NewWithClaims(jwt.SigningMethodRS256, jwt.MapClaims{
		"sub":           claims.Sub,
		"workspace_id":  claims.WorkspaceID,
		"role":          claims.Role,
		"platform_role": claims.PlatformRole,
		"state_id":      claims.StateID,
		"mfa_verified":  claims.MFAVerified,            // F-007 (M17 wave 1): second-factor state for mandatory-MFA roles
		"impersonation": claims.Impersonation,          // S5-G1: read-only admin-impersonation marker (false for normal tokens)
		"iss":           jwtIssuer,                     // F-103: bind issuer
		"aud":           jwt.ClaimStrings{jwtAudience}, // F-103: bind audience
		"exp":           now.Add(s.config.AccessTokenExpiry).Unix(),
		"iat":           now.Unix(),
	})

	return token.SignedString(s.privateKey)
}

func (s *jwtService) ParseAccessToken(ctx context.Context, tokenStr string) (*TokenClaims, error) {
	token, err := jwt.Parse(tokenStr, func(token *jwt.Token) (interface{}, error) {
		if _, ok := token.Method.(*jwt.SigningMethodRSA); !ok {
			return nil, fmt.Errorf("unexpected signing method: %v", token.Header["alg"])
		}
		return s.publicKey, nil
	},
		// F-103: reject tokens not issued for this service (token confusion /
		// cross-service replay) by enforcing the issuer + audience binding.
		jwt.WithIssuer(jwtIssuer),
		jwt.WithAudience(jwtAudience),
	)
	if err != nil {
		return nil, err
	}

	mapClaims, ok := token.Claims.(jwt.MapClaims)
	if !ok || !token.Valid {
		return nil, errors.New("invalid token")
	}

	exp, _ := mapClaims.GetExpirationTime()
	var expiresAt time.Time
	if exp != nil {
		expiresAt = exp.Time
	}

	platformRole, _ := mapClaims["platform_role"].(string)
	if platformRole == "" {
		platformRole = "photographer"
	}

	// F-007 (M17 wave 1): mfa_verified is optional — legacy tokens without the
	// claim parse as false. The type assertion pattern is the same as the other
	// optional fields above.
	mfaVerified, _ := mapClaims["mfa_verified"].(bool)

	// S5-G1: impersonation is optional — legacy/normal tokens without the claim
	// parse as false (read-write). Only admin-minted impersonation tokens set it.
	impersonation, _ := mapClaims["impersonation"].(bool)

	return &TokenClaims{
		Sub:           mapClaims["sub"].(string),
		WorkspaceID:   mapClaims["workspace_id"].(string),
		Role:          mapClaims["role"].(string),
		PlatformRole:  platformRole,
		StateID:       mapClaims["state_id"].(string),
		MFAVerified:   mfaVerified,
		Impersonation: impersonation,
		ExpiresAt:     expiresAt,
	}, nil
}

func (s *jwtService) generateRefreshTokenString() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return fmt.Sprintf("%x", b), nil
}

// enforceSessionLimit checks whether creating a new session for the
// given (user, family) pair would exceed MaxSessions. A rotate within
// an existing family does not count as a new session. Returns an error
// if the limit would be exceeded.
func (s *jwtService) enforceSessionLimit(ctx context.Context, userID, familyID string) error {
	hasFamily, err := s.refreshStore.UserHasFamily(ctx, userID, familyID)
	if err != nil {
		return fmt.Errorf("refresh store: check existing family: %w", err)
	}
	if hasFamily {
		return nil // rotating within an existing family is always allowed
	}
	active, err := s.refreshStore.CountActiveFamiliesForUser(ctx, userID)
	if err != nil {
		return fmt.Errorf("refresh store: count active families: %w", err)
	}
	if active >= s.config.MaxSessions {
		return errors.New("max concurrent sessions exceeded")
	}
	return nil
}

func (s *jwtService) GenerateRefreshToken(ctx context.Context, userID, familyID string) (string, error) {
	if err := s.enforceSessionLimit(ctx, userID, familyID); err != nil {
		return "", err
	}

	tokenStr, err := s.generateRefreshTokenString()
	if err != nil {
		return "", err
	}

	if err := s.refreshStore.Create(ctx, RefreshSessionEntry{
		RawToken:  tokenStr,
		Sub:       userID,
		FamilyID:  familyID,
		ExpiresAt: time.Now().Add(s.config.RefreshTokenExpiry),
	}); err != nil {
		return "", fmt.Errorf("refresh store: create: %w", err)
	}
	return tokenStr, nil
}

func (s *jwtService) GenerateRefreshTokenWithClaims(ctx context.Context, userID, familyID, workspaceID, role, platformRole, stateID string) (string, error) {
	// Backward-compatible wrapper: legacy callers that don't know about
	// MFA state get mfa_verified=false, matching their pre-M17 semantics.
	return s.GenerateRefreshTokenWithMFA(ctx, userID, familyID, workspaceID, role, platformRole, stateID, false)
}

// GenerateRefreshTokenWithMFA is the F-007 variant that persists the
// mfa_verified state of the minting login. The VerifyTOTP handler calls
// this with mfaVerified=true after a successful second-factor check so
// that subsequent access-token refreshes preserve the MFA claim.
func (s *jwtService) GenerateRefreshTokenWithMFA(ctx context.Context, userID, familyID, workspaceID, role, platformRole, stateID string, mfaVerified bool) (string, error) {
	if err := s.enforceSessionLimit(ctx, userID, familyID); err != nil {
		return "", err
	}

	tokenStr, err := s.generateRefreshTokenString()
	if err != nil {
		return "", err
	}

	if err := s.refreshStore.Create(ctx, RefreshSessionEntry{
		RawToken:     tokenStr,
		Sub:          userID,
		FamilyID:     familyID,
		WorkspaceID:  workspaceID,
		Role:         role,
		PlatformRole: platformRole,
		StateID:      stateID,
		MFAVerified:  mfaVerified,
		ExpiresAt:    time.Now().Add(s.config.RefreshTokenExpiry),
	}); err != nil {
		return "", fmt.Errorf("refresh store: create: %w", err)
	}
	return tokenStr, nil
}

func (s *jwtService) RotateRefreshToken(ctx context.Context, oldToken string) (string, string, error) {
	entry, err := s.refreshStore.Get(ctx, oldToken)
	if err != nil {
		if errors.Is(err, ErrRefreshNotFound) {
			return "", "", errors.New("refresh token not found")
		}
		return "", "", fmt.Errorf("refresh store: get: %w", err)
	}

	// Check family revocation first — if the family is dead, nothing
	// under it can be rotated, even if the individual row looks clean.
	familyRevoked, err := s.refreshStore.IsFamilyRevoked(ctx, entry.FamilyID)
	if err != nil {
		return "", "", fmt.Errorf("refresh store: check family revocation: %w", err)
	}
	if entry.Revoked || familyRevoked {
		// Token reuse detected (or the whole family is already dead).
		// Kill the family again for idempotency.
		_ = s.refreshStore.RevokeFamily(ctx, entry.FamilyID)
		return "", "", errors.New("refresh token reuse detected, family revoked")
	}

	if entry.Used {
		// Seeing a second Rotate for the same token means an attacker
		// has the refresh secret. Nuke the family.
		_ = s.refreshStore.RevokeFamily(ctx, entry.FamilyID)
		return "", "", errors.New("refresh token reuse detected, family revoked")
	}

	if time.Now().After(entry.ExpiresAt) {
		return "", "", errors.New("refresh token expired")
	}

	// Mark the old token used BEFORE issuing the new one so a racing
	// rotate hits the reuse-detection path.
	if err := s.refreshStore.MarkUsed(ctx, oldToken); err != nil {
		return "", "", fmt.Errorf("refresh store: mark used: %w", err)
	}

	// Generate the new refresh token (sliding window) and persist it.
	newTokenStr, err := s.generateRefreshTokenString()
	if err != nil {
		return "", "", err
	}
	if err := s.refreshStore.Create(ctx, RefreshSessionEntry{
		RawToken:     newTokenStr,
		Sub:          entry.Sub,
		FamilyID:     entry.FamilyID,
		WorkspaceID:  entry.WorkspaceID,
		Role:         entry.Role,
		PlatformRole: entry.PlatformRole,
		StateID:      entry.StateID,
		MFAVerified:  entry.MFAVerified, // F-007 wave 2: preserve MFA state through rotation
		ExpiresAt:    time.Now().Add(s.config.RefreshTokenExpiry),
	}); err != nil {
		return "", "", fmt.Errorf("refresh store: create rotated: %w", err)
	}

	// Generate the new access token — carry forward claims from the
	// original login. Defaults preserve the pre-F-006-Part-B behavior.
	wsID := entry.WorkspaceID
	role := entry.Role
	pRole := entry.PlatformRole
	stID := entry.StateID
	if wsID == "" {
		wsID = "pending-onboarding"
	}
	if role == "" {
		role = "Owner"
	}
	if pRole == "" {
		pRole = "photographer"
	}
	if stID == "" {
		stID = "pending-onboarding"
	}

	s.mu.Lock()
	accessToken, err := s.generateAccessTokenUnlocked(TokenClaims{
		Sub:          entry.Sub,
		WorkspaceID:  wsID,
		Role:         role,
		PlatformRole: pRole,
		StateID:      stID,
		MFAVerified:  entry.MFAVerified, // F-007 wave 2: carry forward MFA state to rotated access token
	})
	s.mu.Unlock()
	if err != nil {
		return "", "", err
	}

	return accessToken, newTokenStr, nil
}

func (s *jwtService) generateAccessTokenUnlocked(claims TokenClaims) (string, error) {
	if claims.PlatformRole == "" {
		claims.PlatformRole = "photographer"
	}
	now := time.Now()
	token := jwt.NewWithClaims(jwt.SigningMethodRS256, jwt.MapClaims{
		"sub":           claims.Sub,
		"workspace_id":  claims.WorkspaceID,
		"role":          claims.Role,
		"platform_role": claims.PlatformRole,
		"state_id":      claims.StateID,
		"mfa_verified":  claims.MFAVerified,            // F-007 (M17 wave 1): carried from caller (RotateRefreshToken sets false until wave 2 adds session-level persistence)
		"impersonation": claims.Impersonation,          // S5-G1: carried from caller; refresh rotation never sets it true (impersonation tokens are non-refreshable access tokens)
		"iss":           jwtIssuer,                     // F-103: bind issuer
		"aud":           jwt.ClaimStrings{jwtAudience}, // F-103: bind audience
		"exp":           now.Add(s.config.AccessTokenExpiry).Unix(),
		"iat":           now.Unix(),
	})
	return token.SignedString(s.privateKey)
}

func (s *jwtService) InspectRefreshToken(ctx context.Context, tokenStr string) (*RefreshTokenInfo, error) {
	entry, err := s.refreshStore.Get(ctx, tokenStr)
	if err != nil {
		if errors.Is(err, ErrRefreshNotFound) {
			return nil, errors.New("refresh token not found")
		}
		return nil, fmt.Errorf("refresh store: get: %w", err)
	}
	return &RefreshTokenInfo{
		Sub:       entry.Sub,
		FamilyID:  entry.FamilyID,
		ExpiresAt: entry.ExpiresAt,
	}, nil
}

func (s *jwtService) RevokeSession(ctx context.Context, familyID string) error {
	if err := s.refreshStore.RevokeFamily(ctx, familyID); err != nil {
		return fmt.Errorf("refresh store: revoke family: %w", err)
	}
	return nil
}

// ──────────────────────────── OAuth Service ────────────────────────────

type OAuthConfig struct {
	ClientID     string
	ClientSecret string
	RedirectURI  string
}

type OAuthService struct {
	config   OAuthConfig
	provider OAuthProvider
	store    UserStore
	mu       sync.Mutex
	states   map[string]string
}

type oauthStatePayload struct {
	Nonce     string `json:"n"`
	ReturnTo  string `json:"r"`
	ExpiresAt int64  `json:"e"`
}

func NewOAuthService(config OAuthConfig, provider OAuthProvider, store UserStore) *OAuthService {
	return &OAuthService{
		config:   config,
		provider: provider,
		store:    store,
		states:   make(map[string]string),
	}
}

// InitiateGoogleAuth builds the Google authorization URL and returns it along
// with the per-request state nonce. The caller (OAuthGoogleCallback's sibling
// OAuthGoogle handler) stores the returned nonce in an HttpOnly, SameSite=Lax
// "oauth_state" cookie and requires the callback's state nonce to equal it
// (S1-G3 / AREA-AUTH-2). This binds the state to the originating browser and
// makes a leaked/replayed state value useless from any other client without
// needing external state storage.
func (s *OAuthService) InitiateGoogleAuth(ctx context.Context, returnTo string) (authURL string, nonce string, err error) {
	_ = ctx

	if s.config.ClientID == "" {
		return "", "", fmt.Errorf("google OAuth not configured: GOOGLE_CLIENT_ID not set")
	}

	nonceBytes := make([]byte, 16)
	if _, err := rand.Read(nonceBytes); err != nil {
		return "", "", err
	}
	nonce = fmt.Sprintf("%x", nonceBytes)
	state := nonce

	if signedState, signErr := s.signState(oauthStatePayload{
		Nonce:     nonce,
		ReturnTo:  returnTo,
		ExpiresAt: time.Now().UTC().Add(10 * time.Minute).Unix(),
	}); signErr == nil && signedState != "" {
		state = signedState
	} else {
		s.mu.Lock()
		s.states[state] = returnTo
		s.mu.Unlock()
	}

	query := url.Values{
		"client_id":     []string{s.config.ClientID},
		"redirect_uri":  []string{s.config.RedirectURI},
		"response_type": []string{"code"},
		"scope":         []string{"openid email profile"},
		"state":         []string{state},
		"access_type":   []string{"offline"},
		"prompt":        []string{"consent"},
	}

	return "https://accounts.google.com/o/oauth2/v2/auth?" + query.Encode(), nonce, nil
}

// HandleGoogleCallback completes the Google OAuth login. cookieNonce is the
// value the OAuthGoogle handler stashed in the HttpOnly "oauth_state" cookie at
// initiate time; the state's embedded nonce must equal it or the callback is
// rejected as a replayed/forged state (S1-G3 / AREA-AUTH-2).
//
// Identity resolution order (S1-G2 / AREA-AUTH-3):
//  1. by (provider, provider_subject) — the stable Google "sub". A repeat
//     login always lands here, so a later email change at Google (or an
//     attacker reusing a victim's email) can never re-point the link.
//  2. by email — first-time linking only. An existing local account is
//     auto-linked ONLY when it is already email-verified; auto-linking to an
//     UNVERIFIED local account would hand it to an attacker who pre-registered
//     the victim's email and never activated it (S1-G1 / AREA-AUTH-4).
//  3. otherwise create a fresh account, born email-verified (Google proved
//     ownership).
func (s *OAuthService) HandleGoogleCallback(ctx context.Context, code, state, cookieNonce string) (*User, string, error) {
	if s.provider == nil || s.store == nil {
		return nil, "", errors.New("oauth service not fully configured")
	}

	returnTo, nonce, ok := s.consumeStateWithNonce(state)
	if !ok {
		return nil, "", errors.New("invalid oauth state")
	}
	// Bind the state to the browser that initiated the flow. The signed-state
	// path carries a nonce; require it to match the cookie set at initiate
	// time so a captured/replayed state value is useless from any other client.
	// (The unsigned in-memory fallback path returns an empty nonce and is not
	// reachable in production, where ClientSecret is always set.)
	if nonce != "" {
		if cookieNonce == "" || subtle.ConstantTimeCompare([]byte(nonce), []byte(cookieNonce)) != 1 {
			return nil, returnTo, errors.New("oauth state nonce mismatch")
		}
	}

	token, err := s.provider.ExchangeCode(ctx, code)
	if err != nil {
		return nil, returnTo, fmt.Errorf("exchange code failed: %w", err)
	}

	profile, err := s.provider.GetProfile(ctx, token)
	if err != nil {
		return nil, returnTo, fmt.Errorf("get profile failed: %w", err)
	}
	// Defense in depth: GetProfile already rejects unverified Google emails,
	// but never trust a profile that slips through with EmailVerified=false.
	if !profile.EmailVerified {
		return nil, returnTo, errors.New("google account email is not verified")
	}

	// (1) Resolve by the stable provider subject first.
	if linked, lookupErr := s.store.FindByProviderSubject(ctx, "google", profile.ProviderID); lookupErr != nil {
		return nil, returnTo, lookupErr
	} else if linked != nil {
		s.backfillProfile(ctx, linked, profile)
		return linked, returnTo, nil
	}

	// (2) Fall back to email for first-time linking.
	existing, err := s.store.FindByEmail(ctx, profile.Email)
	if err != nil {
		return nil, returnTo, err
	}
	if existing != nil {
		// Only auto-link to an already-verified local account. Refusing the
		// unverified case defeats the pre-registration account-takeover (S1-G1).
		if !existing.EmailVerified {
			return nil, returnTo, errors.New("cannot link Google to an unverified local account")
		}
		_ = s.store.LinkOAuth(ctx, existing.ID, "google", profile.ProviderID)
		s.backfillProfile(ctx, existing, profile)
		return existing, returnTo, nil
	}

	// (3) Create a new user from the Google-verified identity.
	idBytes := make([]byte, 16)
	if _, err := rand.Read(idBytes); err != nil {
		return nil, returnTo, err
	}

	newUser := &User{
		ID:            fmt.Sprintf("%x", idBytes),
		Email:         profile.Email,
		DisplayName:   profile.DisplayName,
		AvatarURL:     profile.AvatarURL,
		EmailVerified: true,
	}

	created, err := s.store.Create(ctx, newUser)
	if err != nil {
		return nil, returnTo, err
	}

	// Born verified: Google proved email ownership, so the local account is
	// activated without the email-OTP step.
	_ = s.store.MarkEmailVerified(ctx, created.ID)
	_ = s.store.LinkOAuth(ctx, created.ID, "google", profile.ProviderID)
	return created, returnTo, nil
}

// backfillProfile fills in an existing account's empty display name / avatar
// from the Google profile. Either field may already be set, in which case it
// is left untouched. No-op when nothing needs backfilling.
func (s *OAuthService) backfillProfile(ctx context.Context, existing *User, profile *OAuthProfile) {
	backfillName := ""
	if existing.DisplayName == "" && profile.DisplayName != "" {
		backfillName = profile.DisplayName
		existing.DisplayName = profile.DisplayName
	}
	backfillAvatar := ""
	if existing.AvatarURL == "" && profile.AvatarURL != "" {
		backfillAvatar = profile.AvatarURL
		existing.AvatarURL = profile.AvatarURL
	}
	if backfillName != "" || backfillAvatar != "" {
		_ = s.store.BackfillProfile(ctx, existing.ID, backfillName, backfillAvatar)
	}
}

func (s *OAuthService) stateSigningKey() []byte {
	if s.config.ClientSecret == "" {
		return nil
	}
	return []byte(s.config.ClientSecret)
}

func (s *OAuthService) signState(payload oauthStatePayload) (string, error) {
	key := s.stateSigningKey()
	if len(key) == 0 {
		return "", nil
	}

	body, err := json.Marshal(payload)
	if err != nil {
		return "", err
	}
	encodedBody := base64.RawURLEncoding.EncodeToString(body)
	mac := hmac.New(sha256.New, key)
	_, _ = mac.Write([]byte(encodedBody))
	sig := mac.Sum(nil)
	return encodedBody + "." + base64.RawURLEncoding.EncodeToString(sig), nil
}

// consumeStateWithNonce validates the OAuth state and returns the returnTo,
// the embedded nonce, and whether the state was accepted. The signed-state
// path returns the nonce so the caller can enforce the HttpOnly cookie binding
// (S1-G3). The unsigned in-memory fallback returns an empty nonce (no binding
// available); it exists only for the no-ClientSecret dev path.
func (s *OAuthService) consumeStateWithNonce(state string) (returnTo string, nonce string, ok bool) {
	if rt, n, signedOK := s.consumeSignedState(state); signedOK {
		return rt, n, true
	}

	s.mu.Lock()
	rt, found := s.states[state]
	if found {
		delete(s.states, state)
	}
	s.mu.Unlock()
	return rt, "", found
}

func (s *OAuthService) consumeSignedState(state string) (returnTo string, nonce string, ok bool) {
	key := s.stateSigningKey()
	if len(key) == 0 {
		return "", "", false
	}

	parts := strings.Split(state, ".")
	if len(parts) != 2 {
		return "", "", false
	}

	mac := hmac.New(sha256.New, key)
	_, _ = mac.Write([]byte(parts[0]))
	expectedSig := mac.Sum(nil)

	actualSig, err := base64.RawURLEncoding.DecodeString(parts[1])
	if err != nil || !hmac.Equal(actualSig, expectedSig) {
		return "", "", false
	}

	body, err := base64.RawURLEncoding.DecodeString(parts[0])
	if err != nil {
		return "", "", false
	}
	var payload oauthStatePayload
	if err := json.Unmarshal(body, &payload); err != nil {
		return "", "", false
	}
	if payload.ExpiresAt < time.Now().UTC().Unix() {
		return "", "", false
	}
	return payload.ReturnTo, payload.Nonce, true
}

// ──────────────────────────── Password Service ────────────────────────────

type PasswordConfig struct {
	ResetOTPExpiry    int // seconds
	MaxFailedAttempts int
	LockoutDuration   int // seconds
}

type PasswordService interface {
	RequestReset(ctx context.Context, email string) error
	ResetPassword(ctx context.Context, email, otp, newPassword string) error
	ValidatePassword(password string) error
}

type passwordService struct {
	config   PasswordConfig
	store    PasswordStore
	notifier SecurityNotifier
	mu       sync.Mutex
	// email -> reset entry
	resets         map[string]*resetEntry
	failedAttempts map[string]int
	// codeGenerator is a seam for tests so they can inject a deterministic
	// OTP generator and exercise the real verification path. Production uses
	// generateCode via the default set in NewPasswordService.
	codeGenerator func(int) (string, error)
}

type resetEntry struct {
	otp       string
	expiresAt time.Time
}

func NewPasswordService(config PasswordConfig, store PasswordStore, notifier SecurityNotifier) PasswordService {
	return &passwordService{
		config:         config,
		store:          store,
		notifier:       notifier,
		resets:         make(map[string]*resetEntry),
		failedAttempts: make(map[string]int),
		codeGenerator:  generateCode,
	}
}

func (s *passwordService) RequestReset(ctx context.Context, email string) error {
	// Always succeed (enumeration protection) - store OTP only if user exists
	code, _ := s.codeGenerator(6)

	// F-031 (audit 2026-05-30): the mutex guards only the in-memory resets map.
	// FindByEmail (DB) and SendPasswordResetOTP (SMTP) touch no shared mutable
	// state, so they must run lock-free — otherwise a single slow DB query or
	// SMTP timeout serializes every concurrent password-reset request behind
	// one global lock (request pile-up / effective DoS on the reset endpoint).
	s.mu.Lock()
	if s.config.ResetOTPExpiry <= 0 {
		// Immediate expiry - set expiresAt to past
		s.resets[email] = &resetEntry{
			otp:       code,
			expiresAt: time.Now().Add(-1 * time.Second),
		}
	} else {
		expiry := time.Duration(s.config.ResetOTPExpiry) * time.Second
		s.resets[email] = &resetEntry{
			otp:       code,
			expiresAt: time.Now().Add(expiry),
		}
	}
	s.mu.Unlock()

	// 2026-05-19: actually send the OTP. The previous implementation
	// generated and stored the code but never delivered it, so the
	// user submitted the forgot-password form, landed on the reset
	// page, and had no code to enter. We look up the user via
	// store.FindByEmail and only call the notifier when the email
	// matches a real account — that preserves the enumeration-defense
	// contract (the HTTP response is identical for registered and
	// unregistered emails) while preventing wasted SMTP traffic for
	// scraping attempts. Errors are logged + swallowed so a transient
	// SMTP outage doesn't leak existence either.
	if s.notifier != nil && s.store != nil && s.config.ResetOTPExpiry > 0 {
		user, lookupErr := s.store.FindByEmail(ctx, email)
		if lookupErr == nil && user != nil {
			if err := s.notifier.SendPasswordResetOTP(ctx, email, code, s.config.ResetOTPExpiry); err != nil {
				log.Printf("password reset: SendPasswordResetOTP to %s failed: %v", maskEmail(email), err)
			}
		}
	}

	return nil
}

func (s *passwordService) ResetPassword(ctx context.Context, email, otp, newPassword string) error {
	if err := s.ValidatePassword(newPassword); err != nil {
		return err
	}

	// F-031 (audit 2026-05-30): the mutex guards only the in-memory
	// failedAttempts/resets maps. The lockout check, OTP comparison, attempt
	// increments, and reset-entry deletion run under the lock; the slow DB
	// (RecordFailedAttempt, UpdatePassword) and SMTP (SendSecurityNotification)
	// calls touch no shared mutable state and run lock-free. Holding the lock
	// across them serialized every concurrent reset behind one global mutex, so
	// a single slow DB write or SMTP timeout could pile up reset requests
	// (effective DoS). We resolve the verification decision under the lock, then
	// release before any external I/O.
	s.mu.Lock()

	// Check lockout
	if s.failedAttempts[email] >= s.config.MaxFailedAttempts {
		s.mu.Unlock()
		return errors.New("account locked due to too many failed attempts")
	}

	entry, ok := s.resets[email]
	if !ok {
		s.failedAttempts[email]++
		s.mu.Unlock()
		_, _ = s.store.RecordFailedAttempt(ctx, email)
		return errors.New("invalid or expired OTP")
	}

	if time.Now().After(entry.expiresAt) {
		s.failedAttempts[email]++
		s.mu.Unlock()
		_, _ = s.store.RecordFailedAttempt(ctx, email)
		return errors.New("OTP expired")
	}

	// Constant-time OTP comparison — audit F-001 (2026-04-10). Previously this
	// function accepted ANY present+unexpired entry, which allowed account
	// takeover. subtle.ConstantTimeCompare returns 0 immediately on length
	// mismatch, which is the desired behavior for fixed-width codes.
	if subtle.ConstantTimeCompare([]byte(entry.otp), []byte(otp)) != 1 {
		s.failedAttempts[email]++
		s.mu.Unlock()
		_, _ = s.store.RecordFailedAttempt(ctx, email)
		return errors.New("invalid OTP")
	}

	// OTP verified — release the lock before any external I/O.
	s.mu.Unlock()

	// Hash the new password before persisting — audit F-001 (2026-05-30).
	// PasswordStore.UpdatePassword writes its argument verbatim into
	// users.password_hash, so passing the raw newPassword stored plaintext
	// credentials on every reset. bcrypt cost 12 matches the ChangePassword
	// path in backend/internal/user/user.go.
	hashed, err := bcrypt.GenerateFromPassword([]byte(newPassword), 12)
	if err != nil {
		return err
	}

	// Update password
	if err := s.store.UpdatePassword(ctx, email, string(hashed)); err != nil {
		return err
	}

	// Clear reset entry only after a successful update (preserves the prior
	// "consume on success" semantics — a failed UpdatePassword leaves the
	// still-valid OTP in place so the user can retry without a new request).
	s.mu.Lock()
	delete(s.resets, email)
	s.mu.Unlock()

	// Send security notification
	_ = s.notifier.SendSecurityNotification(ctx, email, "Your password has been changed")

	return nil
}

func (s *passwordService) ValidatePassword(password string) error {
	if len(password) < 8 {
		return errors.New("password must be at least 8 characters")
	}
	// F-056: cap length so overlong inputs never reach bcrypt.
	if err := passwordpolicy.ValidateBcryptInput("password", password); err != nil {
		return err
	}

	hasUpper := false
	hasLower := false
	hasDigit := false
	for _, c := range password {
		if c >= 'A' && c <= 'Z' {
			hasUpper = true
		}
		if c >= 'a' && c <= 'z' {
			hasLower = true
		}
		if c >= '0' && c <= '9' {
			hasDigit = true
		}
	}

	if !hasUpper {
		return errors.New("password must contain at least one uppercase letter")
	}
	if !hasLower {
		return errors.New("password must contain at least one lowercase letter")
	}
	if !hasDigit {
		return errors.New("password must contain at least one digit")
	}

	return nil
}
