package auth

import (
	"context"
	"crypto/rand"
	"crypto/rsa"
	"crypto/subtle"
	"errors"
	"fmt"
	"log"
	"math/big"
	"net/url"
	"sync"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"golang.org/x/crypto/bcrypt"
)

// ──────────────────────────── Types ────────────────────────────

type User struct {
	ID          string
	Email       string
	DisplayName string
	AvatarURL   string
}

type OAuthToken struct {
	AccessToken string
}

type OAuthProfile struct {
	Email       string
	DisplayName string
	AvatarURL   string
	ProviderID  string
}

// ──────────────────────────── Interfaces ────────────────────────────

type EmailDelivery interface {
	SendOTP(ctx context.Context, email, code string) error
}

type OAuthProvider interface {
	ExchangeCode(ctx context.Context, code string) (*OAuthToken, error)
	GetProfile(ctx context.Context, token *OAuthToken) (*OAuthProfile, error)
}

type UserStore interface {
	FindByEmail(ctx context.Context, email string) (*User, error)
	Create(ctx context.Context, u *User) (*User, error)
	LinkOAuth(ctx context.Context, userID, provider, providerID string) error
	// BackfillProfile updates empty display name and/or avatar URL, e.g.
	// when an email-registered user later signs in via Google and the
	// profile provides data they did not enter during registration.
	// Either field may be empty to skip that update.
	BackfillProfile(ctx context.Context, userID, displayName, avatarURL string) error
}

type SecurityNotifier interface {
	SendSecurityNotification(ctx context.Context, email, message string) error
	// 2026-05-19: SendPasswordResetOTP delivers the 6-digit one-time
	// code generated by RequestReset. Previously RequestReset only
	// stashed the OTP in memory and never emailed it — the user saw
	// the "redirecting to reset page" message and then sat on
	// /reset-password with no code to enter. Implementations should
	// log + suppress send failures rather than propagate (the
	// enumeration-defense contract requires RequestReset to look
	// identical for registered and unregistered emails regardless
	// of email-transport state).
	SendPasswordResetOTP(ctx context.Context, email, code string, expirySeconds int) error
}

type PasswordStore interface {
	FindByEmail(ctx context.Context, email string) (*User, error)
	UpdatePassword(ctx context.Context, email, hashedPassword string) error
	RecordFailedAttempt(ctx context.Context, email string) (int, error)
	IsLocked(ctx context.Context, email string) (bool, error)
}

// ──────────────────────────── OTP Service ────────────────────────────

type OTPConfig struct {
	CodeLength      int
	Expiry          time.Duration
	MaxAttempts     int
	RateLimitMax    int
	RateLimitWindow time.Duration
}

type otpEntry struct {
	code      string
	expiresAt time.Time
	attempts  int
	used      bool
}

type OTPService interface {
	Generate(ctx context.Context, identifier string) (string, error)
	Validate(ctx context.Context, identifier, code string) (bool, error)
}

type otpService struct {
	config   OTPConfig
	delivery EmailDelivery
	mu       sync.Mutex
	entries  map[string]*otpEntry
	// rate limiting: identifier -> list of generation timestamps
	rateLog map[string][]time.Time
}

func NewOTPService(config OTPConfig) OTPService {
	return &otpService{
		config:  config,
		entries: make(map[string]*otpEntry),
		rateLog: make(map[string][]time.Time),
	}
}

func NewOTPServiceWithDelivery(config OTPConfig, delivery EmailDelivery) OTPService {
	return &otpService{
		config:   config,
		delivery: delivery,
		entries:  make(map[string]*otpEntry),
		rateLog:  make(map[string][]time.Time),
	}
}

func generateCode(length int) (string, error) {
	code := ""
	for i := 0; i < length; i++ {
		n, err := rand.Int(rand.Reader, big.NewInt(10))
		if err != nil {
			return "", err
		}
		code += fmt.Sprintf("%d", n.Int64())
	}
	return code, nil
}

func (s *otpService) Generate(ctx context.Context, identifier string) (string, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	// Rate limiting
	now := time.Now()
	windowStart := now.Add(-s.config.RateLimitWindow)
	var recent []time.Time
	for _, t := range s.rateLog[identifier] {
		if t.After(windowStart) {
			recent = append(recent, t)
		}
	}
	if len(recent) >= s.config.RateLimitMax {
		return "", errors.New("rate limit exceeded")
	}

	code, err := generateCode(s.config.CodeLength)
	if err != nil {
		return "", err
	}

	s.entries[identifier] = &otpEntry{
		code:      code,
		expiresAt: now.Add(s.config.Expiry),
		attempts:  0,
		used:      false,
	}
	s.rateLog[identifier] = append(recent, now)

	if s.delivery != nil {
		if err := s.delivery.SendOTP(ctx, identifier, code); err != nil {
			return "", err
		}
	}

	return code, nil
}

func (s *otpService) Validate(ctx context.Context, identifier, code string) (bool, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	entry, ok := s.entries[identifier]
	if !ok {
		return false, nil
	}

	if entry.attempts >= s.config.MaxAttempts {
		return false, errors.New("max attempts exceeded")
	}

	if entry.used {
		return false, nil
	}

	if time.Now().After(entry.expiresAt) {
		return false, nil
	}

	entry.attempts++

	if entry.code != code {
		if entry.attempts >= s.config.MaxAttempts {
			// Already counted, next call will error
		}
		return false, nil
	}

	entry.used = true
	return true, nil
}

// ──────────────────────────── JWT Service ────────────────────────────

type JWTConfig struct {
	AccessTokenExpiry  time.Duration
	RefreshTokenExpiry time.Duration
	MaxSessions        int
}

type TokenClaims struct {
	Sub          string
	WorkspaceID  string
	Role         string // Workspace role: Owner/Admin/Editor/Viewer
	PlatformRole string // Platform role: super_admin/admin/dealer/photographer/team_member/client
	StateID      string
	// F-007 (M17 hardening wave 1): MFAVerified is true iff this access token
	// was issued after a successful TOTP verification in the login flow.
	// Middleware gates TOTP-mandatory roles (platform_admin, platform_staff,
	// workspace_owner, workspace_admin, workspace_member) on MFAVerified==true
	// OR an active grace window (users.mfa_grace_until).
	// Zero value (false) is the safe default for legacy tokens without the claim.
	MFAVerified bool
	ExpiresAt   time.Time
}

type RefreshTokenInfo struct {
	Sub       string
	FamilyID  string
	ExpiresAt time.Time
}

type JWTService interface {
	GenerateAccessToken(ctx context.Context, claims TokenClaims) (string, error)
	ParseAccessToken(ctx context.Context, tokenStr string) (*TokenClaims, error)
	GenerateRefreshToken(ctx context.Context, userID, familyID string) (string, error)
	GenerateRefreshTokenWithClaims(ctx context.Context, userID, familyID, workspaceID, role, platformRole, stateID string) (string, error)
	// F-007 (M17 wave 2): variant that persists the mfa_verified state
	// of the minting login. RotateRefreshToken carries this forward so
	// refreshed access tokens keep their MFA state.
	GenerateRefreshTokenWithMFA(ctx context.Context, userID, familyID, workspaceID, role, platformRole, stateID string, mfaVerified bool) (string, error)
	RotateRefreshToken(ctx context.Context, oldToken string) (newAccess string, newRefresh string, err error)
	InspectRefreshToken(ctx context.Context, tokenStr string) (*RefreshTokenInfo, error)
	RevokeSession(ctx context.Context, familyID string) error
}

// refreshEntry is removed in F-006 Part B — state lives in
// RefreshSessionStore / RefreshSessionEntry now (see refresh_session_store.go).

type jwtService struct {
	config     JWTConfig
	privateKey *rsa.PrivateKey
	publicKey  *rsa.PublicKey
	mu         sync.Mutex
	// F-006 Part B (audit 2026-04-10): refresh session state lives
	// behind the RefreshSessionStore interface so production can wire a
	// DB-backed implementation (survives restarts, multi-instance safe)
	// while tests continue to use the default in-memory store.
	refreshStore RefreshSessionStore
}

func NewJWTService(config JWTConfig) JWTService {
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		panic("failed to generate RSA key: " + err.Error())
	}
	return &jwtService{
		config:       config,
		privateKey:   key,
		publicKey:    &key.PublicKey,
		refreshStore: NewInMemoryRefreshStore(),
	}
}

// WithRefreshStore replaces the default in-memory refresh session store
// with a caller-provided implementation. main.go uses this during
// bootstrap to wire the DB-backed RefreshSessionRepo so refresh sessions
// survive service restarts (F-006 Part B). Returns the same service
// pointer for call chaining. Passing nil is a no-op — the existing
// in-memory store is retained.
func (s *jwtService) WithRefreshStore(store RefreshSessionStore) JWTService {
	if store == nil {
		return s
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.refreshStore = store
	return s
}

func (s *jwtService) GenerateAccessToken(ctx context.Context, claims TokenClaims) (string, error) {
	if claims.Sub == "" || claims.WorkspaceID == "" || claims.Role == "" || claims.StateID == "" {
		return "", errors.New("missing required claims")
	}
	if claims.PlatformRole == "" {
		claims.PlatformRole = "photographer"
	}

	now := time.Now()
	token := jwt.NewWithClaims(jwt.SigningMethodRS256, jwt.MapClaims{
		"sub":           claims.Sub,
		"workspace_id":  claims.WorkspaceID,
		"role":          claims.Role,
		"platform_role": claims.PlatformRole,
		"state_id":      claims.StateID,
		"mfa_verified":  claims.MFAVerified, // F-007 (M17 wave 1): second-factor state for mandatory-MFA roles
		"exp":           now.Add(s.config.AccessTokenExpiry).Unix(),
		"iat":           now.Unix(),
	})

	return token.SignedString(s.privateKey)
}

func (s *jwtService) ParseAccessToken(ctx context.Context, tokenStr string) (*TokenClaims, error) {
	token, err := jwt.Parse(tokenStr, func(token *jwt.Token) (interface{}, error) {
		if _, ok := token.Method.(*jwt.SigningMethodRSA); !ok {
			return nil, fmt.Errorf("unexpected signing method: %v", token.Header["alg"])
		}
		return s.publicKey, nil
	})
	if err != nil {
		return nil, err
	}

	mapClaims, ok := token.Claims.(jwt.MapClaims)
	if !ok || !token.Valid {
		return nil, errors.New("invalid token")
	}

	exp, _ := mapClaims.GetExpirationTime()
	var expiresAt time.Time
	if exp != nil {
		expiresAt = exp.Time
	}

	platformRole, _ := mapClaims["platform_role"].(string)
	if platformRole == "" {
		platformRole = "photographer"
	}

	// F-007 (M17 wave 1): mfa_verified is optional — legacy tokens without the
	// claim parse as false. The type assertion pattern is the same as the other
	// optional fields above.
	mfaVerified, _ := mapClaims["mfa_verified"].(bool)

	return &TokenClaims{
		Sub:          mapClaims["sub"].(string),
		WorkspaceID:  mapClaims["workspace_id"].(string),
		Role:         mapClaims["role"].(string),
		PlatformRole: platformRole,
		StateID:      mapClaims["state_id"].(string),
		MFAVerified:  mfaVerified,
		ExpiresAt:    expiresAt,
	}, nil
}

func (s *jwtService) generateRefreshTokenString() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return fmt.Sprintf("%x", b), nil
}

// enforceSessionLimit checks whether creating a new session for the
// given (user, family) pair would exceed MaxSessions. A rotate within
// an existing family does not count as a new session. Returns an error
// if the limit would be exceeded.
func (s *jwtService) enforceSessionLimit(ctx context.Context, userID, familyID string) error {
	hasFamily, err := s.refreshStore.UserHasFamily(ctx, userID, familyID)
	if err != nil {
		return fmt.Errorf("refresh store: check existing family: %w", err)
	}
	if hasFamily {
		return nil // rotating within an existing family is always allowed
	}
	active, err := s.refreshStore.CountActiveFamiliesForUser(ctx, userID)
	if err != nil {
		return fmt.Errorf("refresh store: count active families: %w", err)
	}
	if active >= s.config.MaxSessions {
		return errors.New("max concurrent sessions exceeded")
	}
	return nil
}

func (s *jwtService) GenerateRefreshToken(ctx context.Context, userID, familyID string) (string, error) {
	if err := s.enforceSessionLimit(ctx, userID, familyID); err != nil {
		return "", err
	}

	tokenStr, err := s.generateRefreshTokenString()
	if err != nil {
		return "", err
	}

	if err := s.refreshStore.Create(ctx, RefreshSessionEntry{
		RawToken:  tokenStr,
		Sub:       userID,
		FamilyID:  familyID,
		ExpiresAt: time.Now().Add(s.config.RefreshTokenExpiry),
	}); err != nil {
		return "", fmt.Errorf("refresh store: create: %w", err)
	}
	return tokenStr, nil
}

func (s *jwtService) GenerateRefreshTokenWithClaims(ctx context.Context, userID, familyID, workspaceID, role, platformRole, stateID string) (string, error) {
	// Backward-compatible wrapper: legacy callers that don't know about
	// MFA state get mfa_verified=false, matching their pre-M17 semantics.
	return s.GenerateRefreshTokenWithMFA(ctx, userID, familyID, workspaceID, role, platformRole, stateID, false)
}

// GenerateRefreshTokenWithMFA is the F-007 variant that persists the
// mfa_verified state of the minting login. The VerifyTOTP handler calls
// this with mfaVerified=true after a successful second-factor check so
// that subsequent access-token refreshes preserve the MFA claim.
func (s *jwtService) GenerateRefreshTokenWithMFA(ctx context.Context, userID, familyID, workspaceID, role, platformRole, stateID string, mfaVerified bool) (string, error) {
	if err := s.enforceSessionLimit(ctx, userID, familyID); err != nil {
		return "", err
	}

	tokenStr, err := s.generateRefreshTokenString()
	if err != nil {
		return "", err
	}

	if err := s.refreshStore.Create(ctx, RefreshSessionEntry{
		RawToken:     tokenStr,
		Sub:          userID,
		FamilyID:     familyID,
		WorkspaceID:  workspaceID,
		Role:         role,
		PlatformRole: platformRole,
		StateID:      stateID,
		MFAVerified:  mfaVerified,
		ExpiresAt:    time.Now().Add(s.config.RefreshTokenExpiry),
	}); err != nil {
		return "", fmt.Errorf("refresh store: create: %w", err)
	}
	return tokenStr, nil
}

func (s *jwtService) RotateRefreshToken(ctx context.Context, oldToken string) (string, string, error) {
	entry, err := s.refreshStore.Get(ctx, oldToken)
	if err != nil {
		if errors.Is(err, ErrRefreshNotFound) {
			return "", "", errors.New("refresh token not found")
		}
		return "", "", fmt.Errorf("refresh store: get: %w", err)
	}

	// Check family revocation first — if the family is dead, nothing
	// under it can be rotated, even if the individual row looks clean.
	familyRevoked, err := s.refreshStore.IsFamilyRevoked(ctx, entry.FamilyID)
	if err != nil {
		return "", "", fmt.Errorf("refresh store: check family revocation: %w", err)
	}
	if entry.Revoked || familyRevoked {
		// Token reuse detected (or the whole family is already dead).
		// Kill the family again for idempotency.
		_ = s.refreshStore.RevokeFamily(ctx, entry.FamilyID)
		return "", "", errors.New("refresh token reuse detected, family revoked")
	}

	if entry.Used {
		// Seeing a second Rotate for the same token means an attacker
		// has the refresh secret. Nuke the family.
		_ = s.refreshStore.RevokeFamily(ctx, entry.FamilyID)
		return "", "", errors.New("refresh token reuse detected, family revoked")
	}

	if time.Now().After(entry.ExpiresAt) {
		return "", "", errors.New("refresh token expired")
	}

	// Mark the old token used BEFORE issuing the new one so a racing
	// rotate hits the reuse-detection path.
	if err := s.refreshStore.MarkUsed(ctx, oldToken); err != nil {
		return "", "", fmt.Errorf("refresh store: mark used: %w", err)
	}

	// Generate the new refresh token (sliding window) and persist it.
	newTokenStr, err := s.generateRefreshTokenString()
	if err != nil {
		return "", "", err
	}
	if err := s.refreshStore.Create(ctx, RefreshSessionEntry{
		RawToken:     newTokenStr,
		Sub:          entry.Sub,
		FamilyID:     entry.FamilyID,
		WorkspaceID:  entry.WorkspaceID,
		Role:         entry.Role,
		PlatformRole: entry.PlatformRole,
		StateID:      entry.StateID,
		MFAVerified:  entry.MFAVerified, // F-007 wave 2: preserve MFA state through rotation
		ExpiresAt:    time.Now().Add(s.config.RefreshTokenExpiry),
	}); err != nil {
		return "", "", fmt.Errorf("refresh store: create rotated: %w", err)
	}

	// Generate the new access token — carry forward claims from the
	// original login. Defaults preserve the pre-F-006-Part-B behavior.
	wsID := entry.WorkspaceID
	role := entry.Role
	pRole := entry.PlatformRole
	stID := entry.StateID
	if wsID == "" {
		wsID = "pending-onboarding"
	}
	if role == "" {
		role = "Owner"
	}
	if pRole == "" {
		pRole = "photographer"
	}
	if stID == "" {
		stID = "pending-onboarding"
	}

	s.mu.Lock()
	accessToken, err := s.generateAccessTokenUnlocked(TokenClaims{
		Sub:          entry.Sub,
		WorkspaceID:  wsID,
		Role:         role,
		PlatformRole: pRole,
		StateID:      stID,
		MFAVerified:  entry.MFAVerified, // F-007 wave 2: carry forward MFA state to rotated access token
	})
	s.mu.Unlock()
	if err != nil {
		return "", "", err
	}

	return accessToken, newTokenStr, nil
}

func (s *jwtService) generateAccessTokenUnlocked(claims TokenClaims) (string, error) {
	if claims.PlatformRole == "" {
		claims.PlatformRole = "photographer"
	}
	now := time.Now()
	token := jwt.NewWithClaims(jwt.SigningMethodRS256, jwt.MapClaims{
		"sub":           claims.Sub,
		"workspace_id":  claims.WorkspaceID,
		"role":          claims.Role,
		"platform_role": claims.PlatformRole,
		"state_id":      claims.StateID,
		"mfa_verified":  claims.MFAVerified, // F-007 (M17 wave 1): carried from caller (RotateRefreshToken sets false until wave 2 adds session-level persistence)
		"exp":           now.Add(s.config.AccessTokenExpiry).Unix(),
		"iat":           now.Unix(),
	})
	return token.SignedString(s.privateKey)
}

func (s *jwtService) InspectRefreshToken(ctx context.Context, tokenStr string) (*RefreshTokenInfo, error) {
	entry, err := s.refreshStore.Get(ctx, tokenStr)
	if err != nil {
		if errors.Is(err, ErrRefreshNotFound) {
			return nil, errors.New("refresh token not found")
		}
		return nil, fmt.Errorf("refresh store: get: %w", err)
	}
	return &RefreshTokenInfo{
		Sub:       entry.Sub,
		FamilyID:  entry.FamilyID,
		ExpiresAt: entry.ExpiresAt,
	}, nil
}

func (s *jwtService) RevokeSession(ctx context.Context, familyID string) error {
	if err := s.refreshStore.RevokeFamily(ctx, familyID); err != nil {
		return fmt.Errorf("refresh store: revoke family: %w", err)
	}
	return nil
}

// ──────────────────────────── OAuth Service ────────────────────────────

type OAuthConfig struct {
	ClientID     string
	ClientSecret string
	RedirectURI  string
}

type OAuthService struct {
	config   OAuthConfig
	provider OAuthProvider
	store    UserStore
	mu       sync.Mutex
	states   map[string]string
}

func NewOAuthService(config OAuthConfig, provider OAuthProvider, store UserStore) *OAuthService {
	return &OAuthService{
		config:   config,
		provider: provider,
		store:    store,
		states:   make(map[string]string),
	}
}

func (s *OAuthService) InitiateGoogleAuth(ctx context.Context, returnTo string) (string, error) {
	_ = ctx

	if s.config.ClientID == "" {
		return "", fmt.Errorf("google OAuth not configured: GOOGLE_CLIENT_ID not set")
	}

	stateBytes := make([]byte, 16)
	if _, err := rand.Read(stateBytes); err != nil {
		return "", err
	}
	state := fmt.Sprintf("%x", stateBytes)

	s.mu.Lock()
	s.states[state] = returnTo
	s.mu.Unlock()

	query := url.Values{
		"client_id":     []string{s.config.ClientID},
		"redirect_uri":  []string{s.config.RedirectURI},
		"response_type": []string{"code"},
		"scope":         []string{"openid email profile"},
		"state":         []string{state},
		"access_type":   []string{"offline"},
		"prompt":        []string{"consent"},
	}

	return "https://accounts.google.com/o/oauth2/v2/auth?" + query.Encode(), nil
}

func (s *OAuthService) HandleGoogleCallback(ctx context.Context, code, state string) (*User, string, error) {
	if s.provider == nil || s.store == nil {
		return nil, "", errors.New("oauth service not fully configured")
	}

	s.mu.Lock()
	returnTo, ok := s.states[state]
	if ok {
		delete(s.states, state)
	}
	s.mu.Unlock()

	if !ok {
		return nil, "", errors.New("invalid oauth state")
	}

	token, err := s.provider.ExchangeCode(ctx, code)
	if err != nil {
		return nil, returnTo, fmt.Errorf("exchange code failed: %w", err)
	}

	profile, err := s.provider.GetProfile(ctx, token)
	if err != nil {
		return nil, returnTo, fmt.Errorf("get profile failed: %w", err)
	}

	existing, err := s.store.FindByEmail(ctx, profile.Email)
	if err != nil {
		return nil, returnTo, err
	}

	if existing != nil {
		_ = s.store.LinkOAuth(ctx, existing.ID, "google", profile.ProviderID)
		// Backfill display name and avatar from Google profile if the user
		// registered via email without providing them.
		backfillName := ""
		if existing.DisplayName == "" && profile.DisplayName != "" {
			backfillName = profile.DisplayName
			existing.DisplayName = profile.DisplayName
		}
		backfillAvatar := ""
		if existing.AvatarURL == "" && profile.AvatarURL != "" {
			backfillAvatar = profile.AvatarURL
			existing.AvatarURL = profile.AvatarURL
		}
		if backfillName != "" || backfillAvatar != "" {
			_ = s.store.BackfillProfile(ctx, existing.ID, backfillName, backfillAvatar)
		}
		return existing, returnTo, nil
	}

	// Create new user
	idBytes := make([]byte, 16)
	if _, err := rand.Read(idBytes); err != nil {
		return nil, returnTo, err
	}

	newUser := &User{
		ID:          fmt.Sprintf("%x", idBytes),
		Email:       profile.Email,
		DisplayName: profile.DisplayName,
		AvatarURL:   profile.AvatarURL,
	}

	created, err := s.store.Create(ctx, newUser)
	if err != nil {
		return nil, returnTo, err
	}

	_ = s.store.LinkOAuth(ctx, created.ID, "google", profile.ProviderID)
	return created, returnTo, nil
}

// ──────────────────────────── Password Service ────────────────────────────

type PasswordConfig struct {
	ResetOTPExpiry    int // seconds
	MaxFailedAttempts int
	LockoutDuration   int // seconds
}

type PasswordService interface {
	RequestReset(ctx context.Context, email string) error
	ResetPassword(ctx context.Context, email, otp, newPassword string) error
	ValidatePassword(password string) error
}

type passwordService struct {
	config   PasswordConfig
	store    PasswordStore
	notifier SecurityNotifier
	mu       sync.Mutex
	// email -> reset entry
	resets         map[string]*resetEntry
	failedAttempts map[string]int
	// codeGenerator is a seam for tests so they can inject a deterministic
	// OTP generator and exercise the real verification path. Production uses
	// generateCode via the default set in NewPasswordService.
	codeGenerator func(int) (string, error)
}

type resetEntry struct {
	otp       string
	expiresAt time.Time
}

func NewPasswordService(config PasswordConfig, store PasswordStore, notifier SecurityNotifier) PasswordService {
	return &passwordService{
		config:         config,
		store:          store,
		notifier:       notifier,
		resets:         make(map[string]*resetEntry),
		failedAttempts: make(map[string]int),
		codeGenerator:  generateCode,
	}
}

func (s *passwordService) RequestReset(ctx context.Context, email string) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	// Always succeed (enumeration protection) - store OTP only if user exists
	code, _ := s.codeGenerator(6)

	if s.config.ResetOTPExpiry <= 0 {
		// Immediate expiry - set expiresAt to past
		s.resets[email] = &resetEntry{
			otp:       code,
			expiresAt: time.Now().Add(-1 * time.Second),
		}
	} else {
		expiry := time.Duration(s.config.ResetOTPExpiry) * time.Second
		s.resets[email] = &resetEntry{
			otp:       code,
			expiresAt: time.Now().Add(expiry),
		}
	}

	// 2026-05-19: actually send the OTP. The previous implementation
	// generated and stored the code but never delivered it, so the
	// user submitted the forgot-password form, landed on the reset
	// page, and had no code to enter. We look up the user via
	// store.FindByEmail and only call the notifier when the email
	// matches a real account — that preserves the enumeration-defense
	// contract (the HTTP response is identical for registered and
	// unregistered emails) while preventing wasted SMTP traffic for
	// scraping attempts. Errors are logged + swallowed so a transient
	// SMTP outage doesn't leak existence either.
	if s.notifier != nil && s.store != nil && s.config.ResetOTPExpiry > 0 {
		user, lookupErr := s.store.FindByEmail(ctx, email)
		if lookupErr == nil && user != nil {
			if err := s.notifier.SendPasswordResetOTP(ctx, email, code, s.config.ResetOTPExpiry); err != nil {
				log.Printf("password reset: SendPasswordResetOTP to %s failed: %v", email, err)
			}
		}
	}

	return nil
}

func (s *passwordService) ResetPassword(ctx context.Context, email, otp, newPassword string) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	// Check lockout
	if s.failedAttempts[email] >= s.config.MaxFailedAttempts {
		return errors.New("account locked due to too many failed attempts")
	}

	entry, ok := s.resets[email]
	if !ok {
		s.failedAttempts[email]++
		_, _ = s.store.RecordFailedAttempt(ctx, email)
		return errors.New("invalid or expired OTP")
	}

	if time.Now().After(entry.expiresAt) {
		s.failedAttempts[email]++
		_, _ = s.store.RecordFailedAttempt(ctx, email)
		return errors.New("OTP expired")
	}

	// Constant-time OTP comparison — audit F-001 (2026-04-10). Previously this
	// function accepted ANY present+unexpired entry, which allowed account
	// takeover. subtle.ConstantTimeCompare returns 0 immediately on length
	// mismatch, which is the desired behavior for fixed-width codes.
	if subtle.ConstantTimeCompare([]byte(entry.otp), []byte(otp)) != 1 {
		s.failedAttempts[email]++
		_, _ = s.store.RecordFailedAttempt(ctx, email)
		return errors.New("invalid OTP")
	}

	// Hash the new password before persisting — audit F-001 (2026-05-30).
	// PasswordStore.UpdatePassword writes its argument verbatim into
	// users.password_hash, so passing the raw newPassword stored plaintext
	// credentials on every reset. bcrypt cost 12 matches the ChangePassword
	// path in backend/internal/user/user.go.
	hashed, err := bcrypt.GenerateFromPassword([]byte(newPassword), 12)
	if err != nil {
		return err
	}

	// Update password
	if err := s.store.UpdatePassword(ctx, email, string(hashed)); err != nil {
		return err
	}

	// Clear reset entry
	delete(s.resets, email)

	// Send security notification
	_ = s.notifier.SendSecurityNotification(ctx, email, "Your password has been changed")

	return nil
}

func (s *passwordService) ValidatePassword(password string) error {
	if len(password) < 8 {
		return errors.New("password must be at least 8 characters")
	}

	hasUpper := false
	hasLower := false
	hasDigit := false
	for _, c := range password {
		if c >= 'A' && c <= 'Z' {
			hasUpper = true
		}
		if c >= 'a' && c <= 'z' {
			hasLower = true
		}
		if c >= '0' && c <= '9' {
			hasDigit = true
		}
	}

	if !hasUpper {
		return errors.New("password must contain at least one uppercase letter")
	}
	if !hasLower {
		return errors.New("password must contain at least one lowercase letter")
	}
	if !hasDigit {
		return errors.New("password must contain at least one digit")
	}

	return nil
}
