# Kustomization for KEDA
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - scaledobjects.yaml
  - gallery-scaledobject.yaml
  - billing-scaledobject.yaml
  - notifications-scaledobject.yaml
