"""Domain services for RawDrive backend."""
from app.services.auth_service import AuthService, TokenPair, AuthUser
from app.services.oauth_service import GoogleOAuthService
from app.services.session_service import SessionService
from app.services.rate_limit_service import RateLimitService, RateLimitType
from app.services.permission_cache import PermissionCacheService, get_permission_cache
from app.services.rbac_service import (
    RBACService,
    Role,
    PermissionCheckResult,
    RBACError,
    RoleNotFoundError,
    RoleExistsError,
    SystemRoleError,
    InvalidPermissionError,
    WORKSPACE_PERMISSIONS,
    PLATFORM_PERMISSIONS,
    create_default_workspace_roles,
)
from app.services.workspace_service import (
    WorkspaceService,
    Workspace,
    WorkspaceMember,
    WorkspaceWithSubscription,
    WorkspaceError,
    WorkspaceNotFoundError,
    WorkspaceAccessDeniedError,
    WorkspaceDisabledError,
    WorkspaceSlugTakenError,
)
from app.services.subscription_service import (
    SubscriptionService,
    Plan,
    SubscriptionStatus,
    LimitType,
    SubscriptionError,
    SubscriptionNotFoundError,
    TierLimitExceededError,
    TrialExpiredError,
    expire_trials_job,
)
from app.services.invitation_service import (
    InvitationService,
    Invitation,
    InvitationError,
    InvitationNotFoundError,
    InvitationExpiredError,
    InvitationAlreadyAcceptedError,
    InvitationRevokedError,
    MemberAlreadyExistsError,
    expire_invitations_job,
)
from app.services.email_verification_service import (
    EmailVerificationService,
    EmailVerificationError,
    TokenExpiredError,
    TokenInvalidError,
    TokenAlreadyUsedError,
    EmailAlreadyVerifiedError,
    ResendCooldownError,
    cleanup_verification_tokens_job,
)
from app.services.email_service import (
    EmailService,
    get_email_service,
    EmailServiceError,
    EmailNotConfiguredError,
    EmailSendError,
    EmailRateLimitError,
    EmailInvalidRecipientError,
    EmailType,
    EmailProvider,
    EmailStatus,
    EmailResult,
    send_verification_email,
    send_welcome_email,
    send_password_reset_email,
)
from app.services.task_queue import (
    TaskQueueService,
    Task,
    TaskStatus,
    TaskPriority,
    get_task_queue,
    enqueue_task,
    register_task_handler,
)
from app.services.tag_service import TagService, get_tag_service, TagError, TagNotFoundError, DuplicateTagError
from app.services.comment_service import CommentService, get_comment_service, CommentError, CommentNotFoundError, CommentForbiddenError
from app.services.people_service import PeopleService, get_people_service, PeopleError, PersonNotFoundError, FaceNotFoundError
from app.services.search_service import SearchService, get_search_service
from app.services.communication_service import CommunicationService, get_communication_service
from app.services.client_tag_service import ClientTagService, get_client_tag_service
from app.services.duplicate_detection_service import DuplicateDetectionService, get_duplicate_detection_service
from app.services.smart_list_service import (
    SmartListService,
    get_smart_list_service,
    SmartListError,
    SmartListNotFoundError,
    SmartListValidationError,
    SmartListDuplicateError,
    SystemSmartListError,
)
from app.services.import_export_service import (
    ImportExportService,
    get_import_export_service,
    ImportExportError,
    ImportValidationError,
    ExportError,
    InvalidFileFormatError,
    EmptyFileError,
    MissingRequiredFieldsError,
)
from app.services.analytics_service import (
    AnalyticsService,
    get_analytics_service,
    AnalyticsError,
    InvalidDateRangeError,
    BatchSizeExceededError,
    InvalidEventError,
    EventNotFoundError,
)
from app.services.compliance_service import (
    ComplianceService,
    get_compliance_service,
    ComplianceError,
    DSRNotFoundError,
    DSRInvalidStatusTransitionError,
    DSRBlockedByLegalHoldError,
    DSRVerificationRequiredError,
    DSRExpiredError,
    DSRAlreadyCompletedError,
    DSRDuplicateRequestError,
    DSRListResult,
    DSRStats,
)
from app.services.legal_hold_service import (
    LegalHoldService,
    get_legal_hold_service,
    LegalHoldError,
    LegalHoldNotFoundError,
    LegalHoldInvalidStatusTransitionError,
    LegalHoldAlreadyActiveError,
    LegalHoldAlreadyReleasedError,
    LegalHoldResourceBlockedError,
    LegalHoldDuplicateResourceError,
    LegalHoldExpiredError,
    LegalHoldListResult,
    LegalHoldStats,
    DeletionCheckResult,
)
from app.services.incident_service import (
    IncidentService,
    get_incident_service,
    IncidentError,
    IncidentNotFoundError,
    IncidentInvalidStatusTransitionError,
    IncidentAlreadyClosedError,
    IncidentAlreadyResolvedError,
    IncidentNotificationOverdueError,
    IncidentAffectedResourceNotFoundError,
    IncidentListResult,
    IncidentStats,
    IncidentUpdateListResult,
    AffectedResourceListResult,
    NotificationDeadlineResult,
)
from app.services.i18n_service import (
    I18nService,
    get_i18n_service,
    I18nServiceError,
    UnsupportedLanguageError,
)


__all__ = [
    # Auth
    "AuthService",
    "TokenPair",
    "AuthUser",
    "GoogleOAuthService",
    # Session
    "SessionService",
    # Rate limiting
    "RateLimitService",
    "RateLimitType",
    # Permission cache
    "PermissionCacheService",
    "get_permission_cache",
    # RBAC
    "RBACService",
    "Role",
    "PermissionCheckResult",
    "RBACError",
    "RoleNotFoundError",
    "RoleExistsError",
    "SystemRoleError",
    "InvalidPermissionError",
    "WORKSPACE_PERMISSIONS",
    "PLATFORM_PERMISSIONS",
    "create_default_workspace_roles",
    # Workspace
    "WorkspaceService",
    "Workspace",
    "WorkspaceMember",
    "WorkspaceWithSubscription",
    "WorkspaceError",
    "WorkspaceNotFoundError",
    "WorkspaceAccessDeniedError",
    "WorkspaceDisabledError",
    "WorkspaceSlugTakenError",
    # Subscription
    "SubscriptionService",
    "Plan",
    "SubscriptionStatus",
    "LimitType",
    "SubscriptionError",
    "SubscriptionNotFoundError",
    "TierLimitExceededError",
    "TrialExpiredError",
    "expire_trials_job",
    # Invitation
    "InvitationService",
    "Invitation",
    "InvitationError",
    "InvitationNotFoundError",
    "InvitationExpiredError",
    "InvitationAlreadyAcceptedError",
    "InvitationRevokedError",
    "MemberAlreadyExistsError",
    "expire_invitations_job",
    # Email Verification
    "EmailVerificationService",
    "EmailVerificationError",
    "TokenExpiredError",
    "TokenInvalidError",
    "TokenAlreadyUsedError",
    "EmailAlreadyVerifiedError",
    "ResendCooldownError",
    "cleanup_verification_tokens_job",
    # Email Service (SMTP/SendGrid)
    "EmailService",
    "get_email_service",
    "EmailServiceError",
    "EmailNotConfiguredError",
    "EmailSendError",
    "EmailRateLimitError",
    "EmailInvalidRecipientError",
    "EmailType",
    "EmailProvider",
    "EmailStatus",
    "EmailResult",
    "send_verification_email",
    "send_welcome_email",
    "send_password_reset_email",
    # Task Queue
    "TaskQueueService",
    "Task",
    "TaskStatus",
    "TaskPriority",
    "get_task_queue",
    "enqueue_task",
    "register_task_handler",
    # Tags
    "TagService",
    "get_tag_service",
    "TagError",
    "TagNotFoundError",
    "DuplicateTagError",
    # Comments
    "CommentService",
    "get_comment_service",
    "CommentError",
    "CommentNotFoundError",
    "CommentForbiddenError",
    # People
    "PeopleService",
    "get_people_service",
    "PeopleError",
    "PersonNotFoundError",
    "FaceNotFoundError",
    # Search
    "SearchService",
    "get_search_service",
    # Communication (Client CRM)
    "CommunicationService",
    "get_communication_service",
    # Client Tags (Client CRM)
    "ClientTagService",
    "get_client_tag_service",
    # Duplicate Detection (Client CRM)
    "DuplicateDetectionService",
    "get_duplicate_detection_service",
    # Smart Lists (Client CRM)
    "SmartListService",
    "get_smart_list_service",
    "SmartListError",
    "SmartListNotFoundError",
    "SmartListValidationError",
    "SmartListDuplicateError",
    "SystemSmartListError",
    # Import/Export (Client CRM)
    "ImportExportService",
    "get_import_export_service",
    "ImportExportError",
    "ImportValidationError",
    "ExportError",
    "InvalidFileFormatError",
    "EmptyFileError",
    "MissingRequiredFieldsError",
    # Analytics (Client CRM)
    "AnalyticsService",
    "get_analytics_service",
    "AnalyticsError",
    "InvalidDateRangeError",
    # Compliance (Audit & Compliance System)
    "ComplianceService",
    "get_compliance_service",
    "ComplianceError",
    "DSRNotFoundError",
    "DSRInvalidStatusTransitionError",
    "DSRBlockedByLegalHoldError",
    "DSRVerificationRequiredError",
    "DSRExpiredError",
    "DSRAlreadyCompletedError",
    "DSRDuplicateRequestError",
    "DSRListResult",
    "DSRStats",
    # Legal Hold (Audit & Compliance System)
    "LegalHoldService",
    "get_legal_hold_service",
    "LegalHoldError",
    "LegalHoldNotFoundError",
    "LegalHoldInvalidStatusTransitionError",
    "LegalHoldAlreadyActiveError",
    "LegalHoldAlreadyReleasedError",
    "LegalHoldResourceBlockedError",
    "LegalHoldDuplicateResourceError",
    "LegalHoldExpiredError",
    "LegalHoldListResult",
    "LegalHoldStats",
    "DeletionCheckResult",
    # Incident Management (Audit & Compliance System)
    "IncidentService",
    "get_incident_service",
    "IncidentError",
    "IncidentNotFoundError",
    "IncidentInvalidStatusTransitionError",
    "IncidentAlreadyClosedError",
    "IncidentAlreadyResolvedError",
    "IncidentNotificationOverdueError",
    "IncidentAffectedResourceNotFoundError",
    "IncidentListResult",
    "IncidentStats",
    "IncidentUpdateListResult",
    "AffectedResourceListResult",
    "NotificationDeadlineResult",
    # I18n (Localization & Regional Features)
    "I18nService",
    "get_i18n_service",
    "I18nServiceError",
    "UnsupportedLanguageError",
]