apiVersion: v1
kind: Service
metadata:
  name: billing-service
  labels:
    app: billing-service
    tier: microservices
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app: billing-service
