/**
 * Generate OpenAPI schemas from all FastAPI microservices.
 *
 * This script fetches OpenAPI specs from running microservices and saves them
 * as JSON files that can be used by orval for TypeScript client generation.
 *
 * Usage:
 *   npx tsx scripts/generate-openapi-schemas.ts
 *
 * Prerequisites:
 *   - All microservices must be running (docker compose up)
 *   - Services must expose /openapi.json endpoint
 */

import * as fs from 'fs';
import * as path from 'path';

interface ServiceConfig {
  name: string;
  port: number;
  basePath?: string; // Default is empty
}

// All RawDrive microservices with their ports
const SERVICES: ServiceConfig[] = [
  { name: 'backend', port: 8000 },
  { name: 'webhooks-service', port: 8003 },
  { name: 'gallery-service', port: 8004 },
  { name: 'billing-service', port: 8005 },
  { name: 'onboarding-service', port: 8006 },
  { name: 'invitations-service', port: 8007 },
  { name: 'upload-service', port: 8008 },
  { name: 'client-service', port: 8009 },
  { name: 'notifications-service', port: 8010 },
  { name: 'ai-service', port: 8011 },
  { name: 'ai-processing-service', port: 8012 },
  { name: 'livesync-service', port: 8013 },
  { name: 'llm-service', port: 8014 },
];

const OUTPUT_DIR = path.join(__dirname, '..', 'packages', 'api-types', 'openapi');

async function fetchOpenApiSpec(service: ServiceConfig): Promise<object | null> {
  const baseUrl = process.env.API_HOST || 'http://localhost';
  const url = `${baseUrl}:${service.port}/openapi.json`;

  console.log(`Fetching OpenAPI spec from ${service.name} (${url})...`);

  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 5000);

    const response = await fetch(url, {
      signal: controller.signal,
      headers: {
        'Accept': 'application/json',
      },
    });

    clearTimeout(timeoutId);

    if (!response.ok) {
      console.warn(`  Warning: ${service.name} returned ${response.status}`);
      return null;
    }

    const spec = await response.json();
    console.log(`  Success: ${service.name} - ${Object.keys(spec.paths || {}).length} endpoints`);
    return spec;
  } catch (error) {
    if (error instanceof Error && error.name === 'AbortError') {
      console.warn(`  Warning: ${service.name} timed out`);
    } else {
      console.warn(`  Warning: ${service.name} not reachable - ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
    return null;
  }
}

function ensureDirectory(dir: string): void {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    console.log(`Created directory: ${dir}`);
  }
}

function writeOpenApiSpec(serviceName: string, spec: object): void {
  const fileName = `${serviceName}.json`;
  const filePath = path.join(OUTPUT_DIR, fileName);

  // Add metadata to the spec
  const enrichedSpec = {
    ...spec,
    'x-generator': {
      name: 'rawdrive-openapi-generator',
      version: '1.0.0',
      generated: new Date().toISOString(),
    },
  };

  fs.writeFileSync(filePath, JSON.stringify(enrichedSpec, null, 2));
  console.log(`  Written: ${filePath}`);
}

async function generateAllSchemas(): Promise<void> {
  console.log('='.repeat(60));
  console.log('RawDrive OpenAPI Schema Generator');
  console.log('='.repeat(60));
  console.log('');

  ensureDirectory(OUTPUT_DIR);

  const results: { service: string; success: boolean; endpoints?: number }[] = [];

  for (const service of SERVICES) {
    const spec = await fetchOpenApiSpec(service);

    if (spec) {
      writeOpenApiSpec(service.name, spec);
      results.push({
        service: service.name,
        success: true,
        endpoints: Object.keys((spec as any).paths || {}).length,
      });
    } else {
      results.push({
        service: service.name,
        success: false,
      });
    }
  }

  // Generate index file that re-exports all specs
  const indexContent = `/**
 * Auto-generated OpenAPI spec index.
 * Generated at: ${new Date().toISOString()}
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Run 'pnpm generate:openapi' to regenerate.
 */

${results
  .filter(r => r.success)
  .map(r => `export { default as ${toCamelCase(r.service)}Spec } from './${r.service}.json';`)
  .join('\n')}

export const AVAILABLE_SERVICES = [
${results
  .filter(r => r.success)
  .map(r => `  '${r.service}',`)
  .join('\n')}
] as const;

export type AvailableService = typeof AVAILABLE_SERVICES[number];
`;

  fs.writeFileSync(path.join(OUTPUT_DIR, 'index.ts'), indexContent);

  // Print summary
  console.log('');
  console.log('='.repeat(60));
  console.log('Generation Summary');
  console.log('='.repeat(60));
  console.log('');

  const successful = results.filter(r => r.success);
  const failed = results.filter(r => !r.success);

  console.log(`Total services: ${SERVICES.length}`);
  console.log(`Successful: ${successful.length}`);
  console.log(`Failed: ${failed.length}`);
  console.log('');

  if (successful.length > 0) {
    console.log('Successful services:');
    successful.forEach(r => {
      console.log(`  - ${r.service}: ${r.endpoints} endpoints`);
    });
  }

  if (failed.length > 0) {
    console.log('');
    console.log('Failed services (ensure they are running):');
    failed.forEach(r => {
      console.log(`  - ${r.service}`);
    });
  }

  console.log('');
  console.log(`Output directory: ${OUTPUT_DIR}`);
  console.log('');
  console.log('Next steps:');
  console.log('  1. Run "pnpm generate:api-clients" to generate TypeScript clients');
  console.log('  2. Import generated clients in your frontend code');
}

function toCamelCase(str: string): string {
  return str
    .replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())
    .replace(/^([a-z])/, (_, letter) => letter.toLowerCase());
}

// Run the generator
generateAllSchemas().catch(error => {
  console.error('Failed to generate OpenAPI schemas:', error);
  process.exit(1);
});
