"""Client token utilities for public gallery visitors.

This module provides utilities for extracting and validating client tokens
from the X-Client-Token header used to identify anonymous gallery visitors.

Feature: 012-client-favorites
"""

from __future__ import annotations

import re
import logging
from typing import Annotated, Optional

from fastapi import Header, HTTPException, status


logger = logging.getLogger(__name__)

# UUID v4 pattern for validation
UUID_PATTERN = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    re.IGNORECASE,
)


def validate_client_token(token: str) -> bool:
    """Validate that a client token is properly formatted.

    Client tokens should be UUID v4 format, generated by the frontend
    using crypto.randomUUID() for uniqueness.

    Args:
        token: The client token to validate

    Returns:
        True if valid UUID v4 format, False otherwise
    """
    if not token or not isinstance(token, str):
        return False

    token = token.strip()
    if not token:
        return False

    # Must be UUID v4 format
    return bool(UUID_PATTERN.match(token))


def extract_client_token(
    x_client_token: Annotated[
        Optional[str],
        Header(alias="X-Client-Token", description="Client identification token"),
    ] = None,
) -> str:
    """Extract and validate client token from request header.

    This is a FastAPI dependency that extracts the X-Client-Token header
    and validates it.

    Args:
        x_client_token: The X-Client-Token header value

    Returns:
        The validated client token

    Raises:
        HTTPException: If token is missing or invalid
    """
    if not x_client_token:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="X-Client-Token header is required",
        )

    token = x_client_token.strip()
    if not validate_client_token(token):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid client token format. Expected UUID v4.",
        )

    return token


# Type alias for dependency injection
ClientToken = Annotated[str, Header(alias="X-Client-Token")]


async def get_client_token(
    x_client_token: ClientToken,
) -> str:
    """FastAPI dependency to get and validate client token.

    Usage:
        @router.post("/favorites")
        async def toggle_favorite(
            client_token: str = Depends(get_client_token),
        ):
            ...

    Args:
        x_client_token: The X-Client-Token header value

    Returns:
        The validated client token

    Raises:
        HTTPException: If token is missing or invalid
    """
    return extract_client_token(x_client_token)
